### PR TITLE
Add support for Forerunner® 165

### PR DESCRIPTION
**Pull request by falsetru**
Thank you for your work. 🙏

I wanted to run this app on my Forerunner 165, but couldn't install through Garmin IQ. Noticed that the model is not listed in the xml files.

- confirmed that the app is running in my own watch.
  - built for Forerunner 165.
  - copied `prg` file to GARMIN/Apps.

### CODE REVIEW

**Comment by dliedke** [comment]
Nice! Can you please confirm it works for 1h meditation? The issue with Forerunner 165 is app memory is not enough for long sessions.

**Comment by dliedke** [comment]
For me it is no good in simulator, I tested this before and could not make it work:

{51B54929-4402-4672-B5E9-B40EEF4B84E7}

**Comment by falsetru** [comment]
1h meditation worked for me.

photo_2024-10-07_22-28-07
photo_2024-10-07_22-28-04
photo_2024-10-07_22-28-02


NOTE: configured to not to record HRV, respiration. I will re-test with HRV detail, respiration  on.

**Comment by dliedke** [comment]
Great news, appreciate all your work and testing. Indeed, we have 3 arrays for each metric, so with HRV and Respiration rate it will use more memory. Let me know the results later.

**Comment by falsetru** [comment]
Including HRV detail, respiration also finished without crash.
But, HRV detail didn't recorded; Maybe because I didn't meditated, just started app, and did other stuffs.

NOTE: Configuration different from default:
- interval alter deleted
- auto save: on
- vibe/sound: Long pulsating

<details>
<summary>screenshots</summary>

photo_2024-10-07_22-50-23
photo_2024-10-07_22-50-25
photo_2024-10-07_22-50-28
photo_2024-10-07_22-50-30
photo_2024-10-07_22-50-32
photo_2024-10-07_22-50-34
photo_2024-10-07_22-50-36
</details>

**Comment by dliedke** [comment]
Thanks a lot! great work and testing, version 8.2.0 is published with your code changes.

**Pull request merged**
